Work/WebApp/Web.Memberships/Controllers/ProductContentController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Web.Memberships.Extensions;

namespace Web.Memberships.Controllers
{
    [Authorize]
    public class ProductContentController : Controller
    {
        // GET: ProductContent
        public async Task<ActionResult> Index(int id)
        {
            var userId = Request.IsAuthenticated ? HttpContext.GetUserId() : null;
            var sections = await SectionExtensions.GetProductSectionsAsync(id, userId);
            return View(sections);
        }

        [Route("ProductContent/Details/{productId:int}/{itemId:int}")]
        public async Task<ActionResult> Details(int productId, int itemId)
        {
            var model = await SectionExtensions.GetContentAsync(productId, itemId);
            return View(model);
        }
    }
}

Work/WebApp/Web.Memberships/Views/ProductContent/Details.cshtml
@model Web.Memberships.Models.ContentViewModel

@{
    ViewBag.Title = "Details";
}

<div class="pc-headline">
    <h2>@Model.Title</h2>
    <a class="btn btn-info btn-sm pull-right" href="@Url.Action("Index", "ProductContent", new { Area = "", id = Model.ProductId })">
        <span class="glyphicon glyphicon-arrow-left"></span>
        Back
    </a>
</div>
<div>@Model.Description</div>

@if (Model.HTML != null)
{
    <div class="article">@Html.Raw(Model.HTML)</div>
}

@if (Model.VideoURL != null)
{
    <div id="video" class="video-margin">&nbsp;</div>
    <div id="hiddenUrl" hidden="hidden">@Model.VideoURL</div>
}

@section scripts
    {
    <script type="text/javascript">
        $(function () {
            //only fire video play back in case it is a video
            if ($("#hiddenUrl").length) {
                var video = $("#hiddenUrl").text();
                //jwVideo(video);

                //https://jwplayer.electroteque.org/youtube
                jwplayer("video").setup({
                    playbackRateControls: true,
                    autostart: false,
                    playlist: [
                        { file: video, type: "mp4" },
                        {
                            sources: [
                                { type: "webm", file: "//videos.electroteque.org/bitrate/elephants_dream_600k.webm" },
                                { type: "mp4", file: "//videos.electroteque.org/bitrate/elephants_dream_600k.mp4" },
                                { type: "ogg", file: "//videos.electroteque.org/bitrate/elephants_dream_600k.ogv" }
                            ]
                        }
                    ],
                    youtube: {

                    }
                });

            }
        });
    </script>
}

Work/WebApp/Web.Memberships/Views/ProductContent/Index.cshtml
@model Web.Memberships.Models.ProductSectionModel

@{
    ViewBag.Title = "Index";
}

@if (Model != null)
{
    <div class="pc-headline">
        <h2>@Model.Title</h2>
        <a class="btn btn-primary btn-sm btn-info pull-right" href="@Url.Action("Index", "Home", new { Area = "" })">
            <span class="glyphicon glyphicon-arrow-left"></span>
            Back
        </a>
    </div>

    if (Model.Sections != null && Model.Sections.Any())
    {
        @Html.Partial("_ProductSectionPartial", Model.Sections)
    }
}

Work/WebApp/Web.Memberships/Views/ProductContent/_ProductItemRowPartial.cshtml
@model Web.Memberships.Models.ProductItemRow

<div class="row product-item">
    <div class="col-sm-2">
        <img src="@Model.ImageUrl" width="140" />
    </div>
    <div class="col-sm-10 text-color line-bottom min-height">
        @if (!Model.IsAvailable)
        {
            <p>Will be relesed: @Model.ReleaseDate.Value.ToShortDateString()</p>
        }
        <h2>
            @if (Model.IsAvailable)
            {
                if (Model.IsDownload)
                {
                    <a href="@Model.Url" target="_blank">@Model.Title</a>
                }
                else
                {
                    <a href="@Url.Action("Details", "ProductContent", new { Area = "", productId = Model.ProductId, itemId = Model.ItemId })">@Model.Title</a>
                }
            }
            else
            {
                @Model.Title
            }
        </h2>
        <p>@Model.Description</p>
    </div>
</div>
<br />

Work/WebApp/Web.Memberships/Views/ProductContent/_ProductSectionPartial.cshtml
@model IEnumerable<Web.Memberships.Models.ProductSection>

@if (Model != null && Model.Any())
{
    foreach (var s in Model)
    {
        <div class="panel panel-success">
            <div class="panel-heading">
                <h4 class="panel-title">
                    @*
                        SiteCarret.js is used to change the play icon
                        data attribute is used by javascirpt to to change the title dynamically
                    *@
                    <a data-toggle="collapse" class="panel-carret" href="#collapse@{@s.Id}" title="Click to collapse @s.Title" data="@s.Title.Replace("\"","'")">
                        <span class="pull-left glyphicon glyphicon-play gly-rotate-90"></span>
                        @s.Title
                    </a>
                </h4>
            </div>
            <div id="collapse@{@s.Id}" class="panel-collapse collapse in">
                <div class="panel-body">
                    @if (s.Items != null && s.Items.Any())
                    {
                        foreach (var item in s.Items)
                        {
                            @Html.Partial("_ProductItemRowPartial", item)
                        }
                    }
                </div>
            </div>
        </div>
        <br />
    }
}